name: "Terraform"
on:
  push:
    branches:
      - main
  pull_request:

env:
  tf_version: 1.3.9
  tflint_version: v0.45.0

concurrency:
  group: ci-pipeline-${{ github.workflow }}-${{ github.event.pull_request.number || github.event.pull_request.head.ref || github.ref }}

jobs:
  linters:
    name: "Terraform Linters"
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.tf_version }}
          terraform_wrapper: false
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v6
        with:
          tflint_version: ${{ env.tflint_version }}
      - name: Setup TFLint cache plugin dir
        uses: actions/cache@v4.3.0
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ hashFiles('.tflint.hcl') }}
      - name: Test code with terraform fmt
        run: terraform fmt --recursive -check=true --diff
        continue-on-error: true
      - name: Test code with TFLint
        continue-on-error: true
        run: |
          tflint --init
          tflint -f compact
      - name: Test code with TFSec
        continue-on-error: true
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          soft_fail: true
      - name: Test code with Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: /
          framework: terraform
          soft_fail: true
          quiet: true
          download_external_modules: false
